import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Planet Facts Site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      test
      {/* <main>
        <NavBar />
        <div>rawr</div>
      </main> */}
    </>
  );
}
