import { NavBar } from "@/components/navbar/NavBar";
import { PLANETS } from "@/lib/planets.constant";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Planet Facts Site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <h1 className={`text-h1 font-antonio`}>DONEC JUSTO EGET</h1>

        <h2 className={`text-h2 font-antonio`}>FELIS FACILISIS FERMENTUM</h2>

        <h3 className={`text-h3 font-spartan text-earth`}>
          ALIUAM PORTTITOR MAURIS SIT AMET ORCI
        </h3>
        <ol className="flex">
          {PLANETS.map((planet, idx) => (
            <li
              key={idx}
              className="p-4 uppercase font-spartan font-bold tracking-wider">
              A {planet}
            </li>
          ))}
        </ol>

        <h4 className={`text-h4 font-spartan`}>
          AENEAN DIGNISSIM PELLENTESQUE FELIS
        </h4>

        <p className={`text-body1 font-spartan font-normal`}>
          Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus
          hendrerit. Pellentesque aliquet nibh nec urna. In nisi neque, aliquet
          vel, dapibus id, mattis vel, nisi. Sed pretium, ligula sollicitudin
          laoreet viverra, tortor libero sodales leo, eget blandit nunc tortor
          eu nibh. Nullam mollis. Ut justo. Suspendisse potenti.Sed egestas,
          ante et vulputate volutpat, eros pede semper est, vitae luctus metus
          libero eu augue. Morbi purus libero, faucibus adipiscing, commodo
          quis, gravida id, est. Sed lectus. Praesent elementum hendrerit
          tortor. Sed semper lorem at felis. Vestibulum volutpat, lacus a
          ultrices sagittis, mi neque euismod dui, eu pulvinar nunc sapien
          ornare nisl. Phasellus pede arcu, dapibus eu, fermentum et, dapibus
          sed, urna. Morbi interdum mollis sapien. Sed ac risus. Phasellus
          lacinia, magna a ullamcorper laoreet, lectus arcu pulvinar risus,
          vitae facilisis libero dolor a purus. Sed vel lacus.
        </p>
      </main>
    </>
  );
}
